version: '3.7'

services:

# RabbitMQ:
 rabbitmq:
  image: 'rabbitmq:3.7-management-alpine'
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
   RABBITMQ_DEFAULT_USER: micro
   RABBITMQ_DEFAULT_PASS: M1cr0
  network_mode: host

# Cafemenu MVN Build JAR's
 cafemenu:
#   container_name: cafemenu-mvn-build
  image: cafemenu_mvn
  volumes:
   - ./docker_m2:/root/.m2
   - ./docker_devm:/home/cafemenu
#    - $HOME/.m2:/root/.m2
#    - ./:/home/cafemenu
  build: .

# Micro-services:
 micro-items:
  container_name: micro-items-c
  ports:
   - "8091:8091"
  depends_on:
   - cafemenu
  build: micro-items/
  network_mode: host

 micro-orders:
  container_name: micro-orders-c
  ports:
   - "8092:8092"
  depends_on:
   - cafemenu
  build: micro-orders/
  network_mode: host

 micro-iteminorders:
  container_name: micro-iteminorders-c
  ports:
   - "8093:8093"
  depends_on:
   - cafemenu
  build: micro-iteminorders/
  network_mode: host

# Web-app:
 web-app-rabbit:
  container_name: web-app-rabbit-c
  build: web-app-rabbit/
  ports:
   - "8090:8090"
  depends_on:
   - micro-items
   - micro-orders
   - micro-iteminorders
  network_mode: host
