version: '3.3'

services:

# Runs Main dockerfile (mvn clean install)
  cafemenu:
   container_name: cafemenu-c
   image: cafemenu_devm
   volumes:
    - .$HOME/.m2:/root/.m2
    - ./dockerbuild:/home/cafemenu
   build: .



# Web-app:
  web-app-rabbit:
   container_name: web-app-rabbit-c
   build: web-app-rabbit/
   ports:
    - "8090:8090"
#   depends_on:
#    - micro-items
#    - micro-orders
#    - micro-iteminorders
   network_mode: host


# Micro's:
#  micro-items:
#   container_name: micro-items-c
#   build: micro-items/
#   ports:
#    - "8091:8091"
#   depends_on:
#    - cafemenu

#  micro-orders:
#   container_name: micro-orders-c
#   build: micro-orders/
#   ports:
#    - "8092:8092"
#   depends_on:
#    - cafemenu

#  micro-iteminorders:
#   container_name: micro-iteminorders-c
#   build: micro-iteminorders/
#   ports:
#    - "8093:8093"
#   depends_on:
#    - cafemenu