version: '3'
services:

  micro-items:
   container_name: micro-items-c
   build: micro-items/
   ports:
    - "8091:8091"

  micro-orders:
   container_name: micro-orders-c
   build: micro-orders/
   ports:
    - "8092:8092"

  micro-iteminorders:
   container_name: micro-iteminorders-c
   build: micro-iteminorders/
   ports:
    - "8093:8093"

  web-app-rabbit:
   container_name: web-app-rabbit-c
   build: web-app-rabbit/
   ports:
    - "8090:8090"
   depends_on:
    - micro-items
    - micro-orders
    - micro-iteminorders
   network_mode: host